---
title: "SID - Percetron"
output: html_document
---

```{r}
# Utils

Swap <- function(df) {
  columns <- names(df)
  columns <- c(columns[length(columns)], columns[1:(length(columns)-1)])
  return (df[, columns])
}

Write <- function(df, filepath, filename) {
  write.table(df, file = paste(filepath, paste("treated", filename, sep = "-"), sep = "/"), quote = FALSE, row.names = FALSE, col.names = FALSE, sep = " ")
  percent = floor(0.75 * nrow(df))
    write.table(df[1:percent,], file = paste(filepath, paste("treated-TRAIN", filename, sep = "-"), sep = "/"), quote = FALSE, row.names = FALSE, col.names = FALSE, sep = " ")
  
  dfp <- df[1:(nrow(df)-percent),]
  dfp <- dfp[1:(nrow(df)-percent),]
    write.table(dfp, file = paste(filepath, paste("treated-TEST", filename, sep = "-"), sep = "/"), quote = FALSE, row.names = FALSE, col.names = FALSE, sep = " ")
}

```

**Pre treatment for breast.cancer.wisconsin.data database**
On remplace 2 (bénigne) par +1 et 4 (maligne) par -1
```{r}
filepath = "/media/mammar/5766C1AE34748499/work/SID/TP-Perceptron"
#filepath = "/home/eudes/ricm5-1/sid/projet/SID"
filename = "breast-cancer-wisconsin.data.txt"

breast.cancer.wisconsin.data <-read.table(paste(filepath, filename, sep = "/"), sep = ",")
df <- breast.cancer.wisconsin.data
df = subset(df, V7!="?")          # on vire les ligne contenant des "?"
df$V7 <- as.numeric(df$V7)        # on reconvertie en numeric
df = subset(df, select = -c(V1))  # on vire la colonne 1

df$V11 <- as.character(df$V11)    # transforme la derniere colone par 1 et -1
df$V11[df$V11 == "2"] <- "1"
df$V11[df$V11 == "4"] <- "-1"
df$V11 <- as.numeric(df$V11)      # on reconvertie en numeric

# on normalise les descripteurs en divisant par leur max
for(column in names(df))
{
  df[column] <- df[column] / max(df[column])
}

# swapping the last column to the first
df <- Swap(df)


head(df)

Write(df, filepath, filename)

```


**Pre treatment for ionosphere.data database**
Le fichier est deja normalisé, on remplace b (bad) par -1, et g (good) par +1
```{r}
filepath = "/media/mammar/5766C1AE34748499/work/SID/TP-Perceptron"
filename = "ionosphere.data.txt"
ionosphere <-read.table(paste(filepath, filename, sep = "/"), sep = ",")

df <-ionosphere
df$V35 <- as.character(df$V35)      # transforme la derniere colone par 1 et -1
df$V35[df$V35 == "b"] <- "-1"
df$V35[df$V35 == "g"] <- "1" 
df$V35 <- as.numeric(df$V35)      # on reconvertie en numeric

# swapping the last column to the first
df <- Swap(df)


head(df)

Write(df, filepath, filename)
```

**Pre treatment for spambase.data database**
On remplace 1 (c'est un spam) par +1 et 0 (non un spam) par +1
```{r}
filepath = "/media/mammar/5766C1AE34748499/work/SID/TP-Perceptron"
filename = "spambase.data.txt"

spambase <-read.table(paste(filepath, filename, sep = "/"), sep = ",")
df <-spambase
df$V58 <- as.character(df$V58)      # transforme la derniere colone par 1 et -1
df$V58[df$V58 == "1"] <- "-1"
df$V58[df$V58 == "0"] <- "1"
df$V58 <- as.numeric(df$V58)

# on normalise les descripteurs en divisant par leur max
for(column in names(df))
{
  df[column] <- df[column] / max(df[column])
}

# swapping the last column to the first
df <- Swap(df)

head(df)

Write(df, filepath, filename)
```


```{r}
evaluate_model <- function (df) {
  indexes <- seq(from = 1, to = nrow(df))
  
  for(i in 1:nrow(df))
  {
    # on tire aleatoirement une valeur d'indice
    index <- sample(indexes, 1)
    indexes <- indexes[-index]
    for(column in names(df))
    {
      value <- df[index, column]
      
    }
    
  }
}



```

```{r}
perceptron_learn <- function(filename)
{
  cmd=paste("./perceptron/perceptron-learn", filename, "HEART-Train-vecteur" ,sep=' ')
  system(cmd)
}
filename = "perceptron/example/HEART-Train"
perceptron_learn(filename)
```

